/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tmp;

import com.fasterxml.jackson.databind.ObjectMapper;

public class App {
    public String getGreeting() {
//        new ObjectMapper();
        return null;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
